@startuml
actor       User       as u1
control     "Nwc\n.exe"     as nwc
control     "Nwc-concat\n.py"      as nwconcpy
control     "Nwc-convert\n.py"      as nwconvpy
control     "Nwc-conv\n.exe"  as nwconvexe
control     "Fluidsynth\n.exe"   as fluid
control     "Ffmpeg\n.exe" as ffmpeg
control     "Lt-generate\n.py" as ltgenerate
control     "Lt-upload\n.ps"    as ltupload
control     "Tenacity\n.exe"  as tenacity
database    "git" as repos
database    "audio folder" as audio
database    "build folder" as build
database    "dist folder" as dist
database    PDrive as pdrive

autonumber
u1 -> nwc : start GUI
u1 -> repos: (manual) create multi .nwctxt's
u1 -[#green]> nwconcpy : run script

' concat
nwconcpy -[#green]> repos: update lied.tex
nwconcpy -[#green]> audio : create labeltrack.txt
nwconcpy -[#green]> build: create merged nwctxt, analysis.txt, structuur.tex

' convert
u1 -[#green]> nwconvpy : run script
nwconvpy -[#green]> nwconvpy: For each Staff:
nwconvpy -[#green]> nwconvexe : call
nwconvexe -[#green]> audio: convert .nwctxt to .mid
build -[#orange]> audio: use merged .nwctxt
audio -[#orange]> audio: use soundfont
nwconvpy -[#green]> fluid : call
fluid -[#green]> audio : convert .mid to.wav
audio -[#orange]> audio: call Fluidsynth
nwconvpy -[#green]> ffmpeg : call
ffmpeg -[#green]> audio : convert .wav to .flac
audio -[#orange]> audio: call Ffmpeg

' lyrics
u1 -> repos: (manual) create liedtekst.tex
build -[#orange]> repos: use analysis.txt

u1 -[#green]> ltgenerate : run script (or call remote API)
ltgenerate -[#green]> dist: render liedtekst .pdf, render structuur .pdf

' upload (in the near future, upload will be after record)
u1 -[#green]> ltupload : run script
ltupload -[#green]> pdrive : upload pdf's to drive

' record
u1 -> tenacity : start GUI
tenacity <[#orange]- audio : import .flacs 
tenacity <[#orange]- audio : import labeltrack
u1 -> tenacity : (manual) make recording
@enduml
